CREATE DATABASE PHP;

USE PHP;

CREATE TABLE usuarios(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(40) NOT NULL UNIQUE,
    SENHA VARCHAR(25) NOT NULL,
    NOME varchar(50) NOT NULL,
    CURSO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
)DEFAULT CHARSET=utf8;