CREATE DATABASE PHP;

USE PHP;

CREATE TABLE Usuarios(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(25) NOT NULL,
    NOME varchar(50) NOT NULL,
    CURSO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE
)DEFAULT CHARSET=utf8;

CREATE TABLE Arquivos(
	ID_Usuario INT NOT NULL PRIMARY KEY, 
    NOME varchar(50) NOT NULL,
    CAMINHO_LOCAL VARCHAR(150) NOT NULL,
    CONSTRAINT fk_IdUsuario FOREIGN KEY (ID_Usuario) REFERENCES Usuarios (ID)
)DEFAULT CHARSET=utf8;